#docker-compose up --build --force-recreate
#docker-compose up db --build --force-recreate
version: '3.7'

services:
  gateway:
      image: nginx
      build:
          context: .
          dockerfile: Dockerfile.Nginx
      ports:
          - 8881:8881
          - 8882:8882
          - 8883:8883
          - 8884:8884
          - 8885:8885
      restart: always

  authorizer:
    build:
      context: .
      dockerfile: Dockerfile.Authorizer.Api
    container_name: Authorizer.Api
    env_file:
      - ./eCommerce.Api.Common.env
    ports:
      - 8081:80
    restart: always

  notifications:
    build:
      context: .
      dockerfile: Dockerfile.Notifications.Api
    container_name: Notifications.Api
    env_file:
      - ./eCommerce.Api.Common.env
    ports:
      - 8082:80
    restart: always

  orders:
      build:
        context: .
        dockerfile: Dockerfile.Orders.Api
      container_name: Orders.Api
      env_file:
        - ./eCommerce.Api.Common.env
      ports:
        - 8083:80
      restart: always

  products:
    build:
      context: .
      dockerfile: Dockerfile.Products.Api
    container_name: Products.Api
    env_file:
      - ./eCommerce.Api.Common.env
    ports:
      - 8084:80
    restart: always
    
  shoppingcart:
    build:
      context: .
      dockerfile: Dockerfile.ShoppingCart.Api
    container_name: ShoppingCart.Api
    env_file:
      - ./eCommerce.Api.Common.env
    ports:
      - 8085:80
    restart: always